#!/usr/bin/env ruby

###
# rom is simple command line bookmark system for Chrome on macos
#
# It can be configured using the ~/.romrc json file. Example
#
# ~/.romrc file:
# {
#   "email": "https://gmail.com"
# }
#
# Usage:
# rom email #=> Opens https://gmail.com in your browser
###

require 'json'

config = JSON.parse(File.read('/Users/whunt/.romrc'))
website = config[ARGV[0]]
if !website.nil?
  cmd = <<-CMD
    open -a "Google Chrome" #{website}
  CMD
  `#{cmd}`
else
  puts "Not recognized #{ARGV[1]}"
end
